### ISSUE TITLE
etherscan provider API

### ISSUE THREAD

**Issue by billtlee** [harmony-one/explorer-v2-backend#1]
Hi,

Quick question about the explorer v2.  I have an app that is using the ethers library to access transaction histories through the etherscan provider on ethereum (https://docs.ethers.io/v5/api/providers/api-providers/#EtherscanProvider).  Will the harmony explorer v2 support this?  Thanks!

**Comment by sophoah** [comment]
@Dewansahil for your info

**Comment by hypnagonia** [comment]
v2 is different app, with different data-structures, trade-offs etc, so it would be too challenging to make and keep api compatible with etherscan provider 

just create an abstraction layer over your history api

**Comment by billtlee** [comment]
@hypnagonia how would i get transaction histories from harmony?  are there any examples you can point me to?  thx!
