### ISSUE TITLE
 Batch failed. Retrying in 2000ms Cannot read properties of undefined (reading 'last_synced_block_number')

### ISSUE THREAD

**Issue by exterity** [harmony-one/explorer-v2-backend#31]
Hello, I try to run this in dev mode, and get this error. How to solve this, please?

> yarn run v1.22.18
$ ts-node  -r tsconfig-paths/register src/index.ts
[index] [2022-03-20T19:25:52.751Z] Harmony Explorer v0.1.1. Git commit hash: 1af21907413a37e1a5e35dd47b22f26f4ee56d41
[index] [2022-03-20T19:25:52.760Z] API is disabled
[indexer/rpc/transport/index] [2022-03-20T19:25:55.124Z] RPC transport: Websocket
[api/controllers/cache/index:cache] [2022-03-20T19:26:00.616Z] LRU cache enabled
[indexer/index] [2022-03-20T19:26:01.690Z] Indexer starting... Shards[0]
[store/postgres/index:shard0] [2022-03-20T19:26:01.730Z] postgres://postgres@localhost:5432/e starting...
[store/postgres/index:shard0] [2022-03-20T19:26:01.730Z] Done
[indexer/rpc/transport/ws/WebSocketRPC:wss://ws.s0.t.hmny.io] [2022-03-20T19:26:03.966Z] Open
[indexer/index] [2022-03-20T19:26:05.094Z] Chain ID set to 1666600000
[indexer/indexer/BlockIndexer:shard0] [2022-03-20T19:26:05.183Z] Created
[indexer/indexer/metrics/walletCount] [2022-03-20T19:26:05.213Z] Wallet counter starting...
[indexer/indexer/metrics/walletCount] [2022-03-20T19:26:05.213Z] Heavy task, make sure you need it enabled
[indexer/indexer/LogIndexer:shard0] [2022-03-20T19:26:05.216Z] Created
[indexer/indexer/contracts/ContractIndexer] [2022-03-20T19:26:05.217Z] Created [erc20, erc721]
[indexer/indexer/contracts/ContractIndexer:erc20] [2022-03-20T19:26:05.218Z] Starting...
[indexer/server/index] [2022-03-20T19:26:05.219Z] Indexer info web server listening at http://localhost:3002
[indexer/indexer/BlockIndexer:shard0] [2022-03-20T19:26:05.229Z] Batch failed. Retrying in 2000ms Cannot read properties of undefined (reading 'last_synced_block_number')
[indexer/indexer/BlockIndexer:shard0] [2022-03-20T19:26:05.231Z] Batch decreased to 900
[indexer/indexer/LogIndexer:shard0] [2022-03-20T19:26:05.348Z] Batch failed. Retrying in 2000ms Cannot read properties of undefined (reading 'last_synced_block_number')
[indexer/indexer/LogIndexer:shard0] [2022-03-20T19:26:05.349Z] Batch decreased to 9
[indexer/indexer/contracts/ContractIndexer:erc20] [2022-03-20T19:26:05.350Z] Batch failed Cannot read properties of undefined (reading 'last_synced_block_number')
[indexer/indexer/contracts/ContractIndexer:erc721] [2022-03-20T19:26:05.350Z] Starting...
[indexer/indexer/contracts/ContractIndexer:erc721] [2022-03-20T19:26:05.351Z] Batch failed Cannot read properties of undefined (reading 'last_synced_block_number')
[indexer/indexer/BlockIndexer:shard0] [2022-03-20T19:26:07.270Z] Batch failed. Retrying in 2000ms Cannot read properties of undefined (reading 'last_synced_block_number')
[indexer/indexer/BlockIndexer:shard0] [2022-03-20T19:26:07.272Z] Batch decreased to 810
[indexer/indexer/LogIndexer:shard0] [2022-03-20T19:26:07.352Z] Batch failed. Retrying in 2000ms Cannot read properties of undefined (reading 'last_synced_block_number')
[indexer/indexer/LogIndexer:shard0] [2022-03-20T19:26:07.353Z] Batch decreased to 8
[indexer/indexer/BlockIndexer:shard0] [2022-03-20T19:26:09.290Z] Batch failed. Retrying in 2000ms Cannot read properties of undefined (reading 'last_synced_block_number')
[indexer/indexer/BlockIndexer:shard0] [2022-03-20T19:26:09.291Z] Batch decreased to 729
[indexer/indexer/LogIndexer:shard0] [2022-03-20T19:26:09.355Z] Batch failed. Retrying in 2000ms Cannot read properties of undefined (reading 'last_synced_block_number')
[indexer/indexer/LogIndexer:shard0] [2022-03-20T19:26:09.356Z] Batch decreased to 7
[indexer/index] [2022-03-20T19:26:10.702Z] Unhandled Rejection at: Promise', [object Promise], 'reason:', TypeError: Cannot read properties of undefined (reading 'last_synced_block_number')

**Comment by ArtemKolodko** [comment]
Hi @[exterity](https://github.com/exterity) you should apply scheme first
You can use this file: https://github.com/harmony-one/explorer-v2-backend/blob/master/src/store/postgres/sql/scheme.sql
Or uncomment [this line] (https://github.com/harmony-one/explorer-v2-backend/blob/master/src/store/postgres/index.ts#L95)

In the next updates will be implemented auto-migration from code
